aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - fd
    - ripgrep
    - bat
    - tree
    - jq
    - jtc
    - gh
    - zip
    - unzip
    - wget
    - direnv
    - curl
    - neovim
    - lunarvim
    - nushell
    - starship
    - carapace
    - cheat
    - fzf
    - zoxide
    - atuin
    - broot
    - tilt
    - kubectl
    - kubectx
    - helm
    - krew
    - dive
    - lazygit
    - wslu
    - wsl-open
    - devbox
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - nushell
    - gh
    - zoxide
    - thefuck
    - starship
    - direnv
    - carapace
    - broot
    - atuin
shell: bash
systems:
    - arch: x86_64
      home: ""
      hostname: DESKTOP-7UE031Q
      os: linux
      user:
        email: roman.weintraub@gmail.com
        name: Roman
        ssh_private_key_file: ""
        ssh_public_key_file: ""
        username: roni
      username: roni
    - arch: x86_64
      home: ""
      hostname: nixos
      os: linux
      user:
        email: roman.weintraub@gmail.com
        name: Roman Weintraub
        ssh_private_key_file: ""
        ssh_public_key_file: ""
        username: nixos
      username: nixos
track: nixos-unstable
unfree: true
users: []
