{ config, pkgs, misc, ... }: {
  # Shared user-level customizations.
  programs.bash.initExtra = "nu && exit";
  programs.nushell = {
    configFile.source = ./config.nu;
    shellAliases = {
       ll = "ls -l";
       la = "ls -la";
    };
  };

  # starship colors are generated by matugen (profiles/matugen/starship.toml.tmpl);
  programs.eza = {
    git = true;
    icons = true;
  };
  programs.atuin.flags = [ "--disable-up-arrow"];
  programs.atuin.settings = {
    inline_height = 20;
    enter_accept = true;
    invert = true;
    filter_mode_shell_up_key_binding = "directory";
  };
}
